In [1]:
from ovo import db, design_logic, descriptor_logic, import_export_logic
import pandas as pd

╭───────────────────────────────────────────── Platform Warning ──────────────────────────────────────────────╮
│ ⚠️  WARNING: Windows Detected ⚠️                                                                            │
│                                                                                                             │
│ OVO workflows use Nextflow which is not supported on Windows.                                               │
│ Please use Linux or macOS, or run OVO in WSL2 (Windows Subsystem for Linux) to enable submitting workflows. │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

OVO home d:\ProyectosUniversidad\BioInformatica\ovo_home

In [2]:
project = db.Project.get(name='OVO Publication Examples 1')
round_ids = db.Round.select_values("id", project_id=project.id)
pool_ids = db.Pool.select_values("id", round_id__in=round_ids)
print(len(pool_ids), 'pools', pool_ids)

10 pools ['efm', 'ogc', 'jov', 'rsj', 'avz', 'mmo', 'qki', 'bbc', 'xeh', 'zuk']

In [3]:
project.id

'b8e657bb-b0b0-423e-9235-383a6d8f74e5'

In [4]:
with pd.option_context('display.max_columns', 100):
    jobs = design_logic.get_design_jobs_table(project.id)
    del jobs[('Job', 'duration')]
    display(jobs)

                                                     Pool  \
                                                     name
(Pool, id)
bbc          4ZXB 1000 designs default weights ligandmpnn
qki                           Top designs diversification
jov                  1A41 6*100*8 designs default weights
zuk                      5IUS 500*5 designs PD1 interface
mmo                          4ZXB 1000 designs beta sheet
avz                     4ZXB 1000 designs default weights
xeh         5IUS 500*5 designs PD1 interface with inpaint
ogc              1A41 6*100*8 designs active site weights
rsj                                4ZXB BindCraft default

                                                                 Job  \
                                                  description status
(Pool, id)
bbc         Insulin receptor miniprotein binders hotspot E...   Done
qki                 Top 2 from each pool by PAE, RMSD and ddG   Done
jov         length 150 with 10-100 residues spacing the ac...   Done
zuk                       PD1 interface, no sequence redesign   Done
mmo         Insulin receptor miniprotein binders hotspot E...   Done
avz         Insulin receptor miniprotein binders hotspot E...   Done
xeh                                PD1 interface, inpaint seq   Done
ogc         length 150 with 10-100 residues spacing the ac...   Done
rsj         Insulin receptor miniprotein binders hotspot E...   Done

                          Designs       Workflow                               \
                 created accepted total    input                         type
(Pool, id)
bbc         3 months ago        3     3      NaN    RFdiffusion binder design
qki         4 months ago       37    37      NaN    RFdiffusion binder design
jov         4 months ago        0     0      NaN  RFdiffusion scaffold design
zuk         4 months ago        1     1      NaN  RFdiffusion scaffold design
mmo         4 months ago        1     1      NaN    RFdiffusion binder design
avz         4 months ago        5     5      NaN    RFdiffusion binder design
xeh         4 months ago      275   275      NaN  RFdiffusion scaffold design
ogc         4 months ago       26    26      NaN  RFdiffusion scaffold design
rsj         4 months ago       13    13      NaN      BindCraft binder design

                                                  RFdiffusion               \
                                                      contigs     hotspots
(Pool, id)
bbc                                         [E6-155/0 50-100]  E64,E88,E96
qki          [62-62/0 B6-155, 71-71/0 B6-155, 70-70/0 B6-155]  B64,B88,B96
jov         [10-100/A56-56/10-100/A100-100/10-100/A125-125...         None
zuk         [0-30/A119-140/15-40/A63-82/0-30/0 C18-27/C53-...         None
mmo                                         [E6-155/0 50-100]  E64,E88,E96
avz                                         [E6-155/0 50-100]  E64,E88,E96
xeh         [0-30/A119-140/15-40/A63-82/0-30/0 C18-27/C53-...         None
ogc         [10-100/A56-56/10-100/A100-100/10-100/A125-125...         None
rsj                                                       NaN          NaN

                                                                  \
           model_weights timesteps partial_diffusion num_designs
(Pool, id)
bbc                 None      50.0             False      1000.0
qki         Complex_beta      20.0              True        50.0
jov                 None      50.0             False       100.0
zuk                 None      50.0             False      1000.0
mmo         Complex_beta      50.0             False      1000.0
avz                 None      50.0             False      1000.0
xeh                 None      50.0             False      1000.0
ogc           ActiveSite      50.0             False       100.0
rsj                  NaN       NaN               NaN         NaN

                                                                  \
           cyclic_offset batch_size contigmap_length inpaint_seq
(Pool, id)
bbc                False      100.0              NaN         NaN
qki                False      100.0              NaN         NaN
jov                False       50.0            150.0         NaN
zuk                False      100.0              NaN         NaN
mmo                False      100.0              NaN         NaN
avz                False      100.0              NaN         NaN
xeh                False      100.0              NaN         NaN
ogc                False       50.0            150.0         NaN
rsj                  NaN        NaN              NaN         NaN

                             \
           backbone_filters
(Pool, id)
bbc                     NaN
qki                     NaN
jov                     NaN
zuk                     NaN
mmo                     NaN
avz                     NaN
xeh                     NaN
ogc                     NaN
rsj                     NaN

                                                                ProteinMPNN  \
                                               run_parameters num_sequences
(Pool, id)
bbc                                                                     4.0
qki                                                                     1.0
jov                                                                     2.0
zuk                                                                     5.0
mmo                                                                     1.0
avz                                                                     1.0
xeh         contigmap.inpaint_seq=[A63/A65/A67/A69/A71-72/...           5.0
ogc                                                                     8.0
rsj                                                       NaN           NaN

                                                                          \
           fastrelax_cycles omit_aa sampling_temp bias_aa run_parameters
(Pool, id)
bbc                     0.0      CX        0.0001
qki                     2.0      CX        0.0001
jov                     0.0      CX        0.1000
zuk                     0.0      CX        0.1000
mmo                     3.0      CX        0.0001
avz                     3.0      CX        0.0001
xeh                     0.0      CX        0.1000
ogc                     0.0      CX        0.1000
rsj                     NaN     NaN           NaN     NaN            NaN

                               Refolding              Thresholds  \
                            primary_test esmfold_fp16   AF2 iPAE
(Pool, id)
bbc         af2_model_1_multimer_tt_3rec        False   ≤ 10.000
qki         af2_model_1_multimer_tt_3rec        False   ≤ 10.000
jov              af2_model_1_ptm_ft_3rec        False        NaN
zuk              af2_model_1_ptm_ft_3rec        False        NaN
mmo         af2_model_1_multimer_tt_3rec        False   ≤ 10.000
avz         af2_model_1_multimer_tt_3rec        False   ≤ 10.000
xeh              af2_model_1_ptm_ft_3rec        False        NaN
ogc              af2_model_1_ptm_ft_3rec        False        NaN
rsj                                  NaN          NaN        NaN

                                                                        \
           AF2 Target-aligned Binder RMSD AF2 Binder pLDDT Rosetta ddG
(Pool, id)
bbc                               ≤ 1.000         ≥ 80.000   ≤ -30.000
qki                               ≤ 2.000         ≥ 80.000   ≤ -30.000
jov                                   NaN              NaN         NaN
zuk                                   NaN              NaN         NaN
mmo                               ≤ 2.000         ≥ 80.000   ≤ -20.000
avz                               ≤ 2.000         ≥ 80.000   ≤ -20.000
xeh                                   NaN              NaN         NaN
ogc                                   NaN              NaN         NaN
rsj                                   NaN              NaN         NaN

                                                                     \
           AF2 Design RMSD AF2 Native Motif RMSD  AF2 PAE AF2 pLDDT
(Pool, id)
bbc                    NaN                   NaN      NaN       NaN
qki                    NaN                   NaN      NaN       NaN
jov                ≤ 2.000               ≤ 1.500  ≤ 5.000  ≥ 80.000
zuk                ≤ 2.000               ≤ 2.000  ≤ 5.000  ≥ 80.000
mmo                    NaN                   NaN      NaN       NaN
avz                    NaN                   NaN      NaN       NaN
xeh                ≤ 2.000               ≤ 2.000  ≤ 5.000  ≥ 80.000
ogc                ≤ 2.000               ≤ 1.500  ≤ 5.000  ≥ 80.000
rsj                    NaN                   NaN      NaN       NaN

               BindCraft                                                     \
           target_chains binder_length     hotspots number_of_final_designs
(Pool, id)
bbc                  NaN           NaN          NaN                     NaN
qki                  NaN           NaN          NaN                     NaN
jov                  NaN           NaN          NaN                     NaN
zuk                  NaN           NaN          NaN                     NaN
mmo                  NaN           NaN          NaN                     NaN
avz                  NaN           NaN          NaN                     NaN
xeh                  NaN           NaN          NaN                     NaN
ogc                  NaN           NaN          NaN                     NaN
rsj                    E        50,100  E64,E88,E96                    20.0

                                                                            \
           time_limit_hours filter_type design_protocol interface_protocol
(Pool, id)
bbc                     NaN         NaN             NaN                NaN
qki                     NaN         NaN             NaN                NaN
jov                     NaN         NaN             NaN                NaN
zuk                     NaN         NaN             NaN                NaN
mmo                     NaN         NaN             NaN                NaN
avz                     NaN         NaN             NaN                NaN
xeh                     NaN         NaN             NaN                NaN
ogc                     NaN         NaN             NaN                NaN
rsj                     6.0     Default         Default         AlphaFold2

                                                                           \
           template_protocol prediction_protocol custom_advanced_settings
(Pool, id)
bbc                      NaN                 NaN                      NaN
qki                      NaN                 NaN                      NaN
jov                      NaN                 NaN                      NaN
zuk                      NaN                 NaN                      NaN
mmo                      NaN                 NaN                      NaN
avz                      NaN                 NaN                      NaN
xeh                      NaN                 NaN                      NaN
ogc                      NaN                 NaN                      NaN
rsj                  Default             Default                       {}


           custom_filter_settings num_replicas
(Pool, id)
bbc                           NaN          NaN
qki                           NaN          NaN
jov                           NaN          NaN
zuk                           NaN          NaN
mmo                           NaN          NaN
avz                           NaN          NaN
xeh                           NaN          NaN
ogc                           NaN          NaN
rsj                            {}          1.0

In [5]:
jobs.to_csv('../../data/results/ovo_publication_examples_1_jobs.csv')

In [6]:
designs = db.Design.select_dataframe(pool_id__in=pool_ids)
designs.head()

,pool_id,structure_path,structure_descriptor_key,accepted,spec,contig_index
id,,,,,,
ovo_avz_0030_cycle02,avz,project/b8e657bb-b0b0-423e-9235-383a6d8f74e5/p...,rfd_ee|proteinmpnn_fastrelax|sequence_structur...,True,"DesignSpec(chains=[DesignChain(type='protein',...",0
ovo_avz_0124_cycle04,avz,project/b8e657bb-b0b0-423e-9235-383a6d8f74e5/p...,rfd_ee|proteinmpnn_fastrelax|sequence_structur...,True,"DesignSpec(chains=[DesignChain(type='protein',...",0
ovo_avz_0299_cycle01,avz,project/b8e657bb-b0b0-423e-9235-383a6d8f74e5/p...,rfd_ee|proteinmpnn_fastrelax|sequence_structur...,True,"DesignSpec(chains=[DesignChain(type='protein',...",0
ovo_avz_0481_cycle03,avz,project/b8e657bb-b0b0-423e-9235-383a6d8f74e5/p...,rfd_ee|proteinmpnn_fastrelax|sequence_structur...,True,"DesignSpec(chains=[DesignChain(type='protein',...",0
ovo_avz_0732_cycle04,avz,project/b8e657bb-b0b0-423e-9235-383a6d8f74e5/p...,rfd_ee|proteinmpnn_fastrelax|sequence_structur...,True,"DesignSpec(chains=[DesignChain(type='protein',...",0

In [7]:
descriptors = descriptor_logic.get_wide_descriptor_table(pool_ids=pool_ids)
descriptors = designs.join(descriptors)
descriptors.head()

D:\ProyectosUniversidad\BioInformatica\ovo\ovo\core\logic\descriptor_logic.py:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, seq_column, pd.Series(sequences_by_design_id))
D:\ProyectosUniversidad\BioInformatica\ovo\ovo\core\logic\descriptor_logic.py:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, seq_column, pd.Series(sequences_by_design_id))
D:\ProyectosUniversidad\BioInformatica\ovo\ovo\core\logic\descriptor_logic.py:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, seq_column, pd.Series(sequences_by_design_id))
D:\ProyectosUniversidad\BioInformatica\ovo\ovo\core\logic\descriptor_logic.py:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(0, seq_column, pd.Series(sequences_by_design_id))

,pool_id,structure_path,structure_descriptor_key,accepted,spec,contig_index,Sequence B,Sequence L,Sequence H,Sequence A,...,Normalized positive top1 patch area at pH 7.4,Negative patch area at pH 7.4,Normalized negative patch area at pH 7.4,Negative top1 patch area at pH 7.4,Normalized negative top1 patch area at pH 7.4,Electrostatic volume integral at pH 7.4,Positive electrostatic regions volume integral at pH 7.4,Negative electrostatic regions volume integral at pH 7.4,Positive electrostatic volume integral at pH 7.4,Negative electrostatic volume integral at pH 7.4
id,,,,,,,,,,,,,,,,,,,,,
ovo_avz_0030_cycle02,avz,project/b8e657bb-b0b0-423e-9235-383a6d8f74e5/p...,rfd_ee|proteinmpnn_fastrelax|sequence_structur...,True,"DesignSpec(chains=[DesignChain(type='protein',...",0,NaN,NaN,NaN,EEEEKYEKLAEVALYGNELVESIKDEEEKEKLAKYVLEVIENREKI...,...,0.008814,2397.582566,0.517766,2397.582566,0.517766,-53204.939693,247.264672,-37802.189478,524.728685,-53729.668377
ovo_avz_0124_cycle04,avz,project/b8e657bb-b0b0-423e-9235-383a6d8f74e5/p...,rfd_ee|proteinmpnn_fastrelax|sequence_structur...,True,"DesignSpec(chains=[DesignChain(type='protein',...",0,NaN,NaN,NaN,KEEELEKLAYEYLEYSIKSYEYKKKAEELEKSEYEDEEKKKKEIEE...,...,0.002133,1329.886461,0.221943,494.351643,0.082502,-29282.013327,1603.259674,-20382.537688,5073.431641,-34355.444969
ovo_avz_0299_cycle01,avz,project/b8e657bb-b0b0-423e-9235-383a6d8f74e5/p...,rfd_ee|proteinmpnn_fastrelax|sequence_structur...,True,"DesignSpec(chains=[DesignChain(type='protein',...",0,NaN,NaN,NaN,MSIEEIKKILEEIKKEAEAKNAKKVAEAAAKDPELAKKLAAELTAE...,...,0.013346,1431.141721,0.264025,1222.315483,0.225499,-31439.230457,1221.440562,-21455.968271,3326.778095,-34766.008552
ovo_avz_0481_cycle03,avz,project/b8e657bb-b0b0-423e-9235-383a6d8f74e5/p...,rfd_ee|proteinmpnn_fastrelax|sequence_structur...,True,"DesignSpec(chains=[DesignChain(type='protein',...",0,NaN,NaN,NaN,MEAALKAAEEEKEFQKQVELAKLMIESYKKEGDEEQAEYWEKILEE...,...,0.004164,2322.248872,0.491070,2295.299667,0.485372,-62153.827602,169.365019,-47174.741642,462.410420,-62616.238021
ovo_avz_0732_cycle04,avz,project/b8e657bb-b0b0-423e-9235-383a6d8f74e5/p...,rfd_ee|proteinmpnn_fastrelax|sequence_structur...,True,"DesignSpec(chains=[DesignChain(type='protein',...",0,NaN,NaN,NaN,EEEEKEKKLKELEKQAKEVEEEGRKKVKEAEAKLKAGDKSEEVKEL...,...,0.026966,1342.739388,0.243623,1156.812464,0.209889,-18930.954449,6064.660410,-19659.415027,11991.801964,-30922.756413

In [8]:
descriptors.shape

(898, 169)

In [9]:
descriptors.to_csv('../../data/results/ovo_examples_all.csv.gz')